config/routes.rb
Rails.application.routes.draw do
  resources :cards, only: [:show]

  root to: 'cards#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/card.rb
class Card < ApplicationRecord
  extend FriendlyId
  friendly_id :name, use: :slugged
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  before_action :set_card, only: [:show, :edit, :update, :destroy]

  def index
    @cards = Card.all
  end

  def show
  end

  def new
    @card = Card.new
  end

  def edit
  end

  def create
    @card = Card.new(card_params)

    respond_to do |format|
      if @card.save
        format.html { redirect_to @card, notice: 'Card was successfully created.' }
        format.json { render :show, status: :created, location: @card }
      else
        format.html { render :new }
        format.json { render json: @card.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @card.update(card_params)
        format.html { redirect_to @card, notice: 'Card was successfully updated.' }
        format.json { render :show, status: :ok, location: @card }
      else
        format.html { render :edit }
        format.json { render json: @card.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @card.destroy
    respond_to do |format|
      format.html { redirect_to cards_url, notice: 'Card was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_card
      @card = Card.friendly.find(params[:id])
    end

    def card_params
      params.require(:card).permit(:name, :birthday, :location, :icon, :front_image, :back_thumb, :color)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/views/cards/_card.html.slim
css:
  .player-photo-front { background-image: url("#{card.front_image}"); }

.card-container.person-card-a-tron
  .person-card
    .face.front
      .team-logo
      .player-photo-front
        .player-number
          | 11
        .player-name-front
          h3 = card.name
    .face.back
      .player-content-back
        .player-identification-back
          .player-photo-back
          .player-name-back
            = card.name
        .player-statistics
          .player-position-title
            | Location
            br/
            span.player-position
              = card.location
          .player-school-title
            | Birthday
            br/
            span.player-school
              = card.birthday
        .honors-divider
          hr/
          p
            | Achievements
          hr/
        .player-honors
          .left-side-honors
            ul
              li All-District 2011-12
              li All-Conference 2011-12
              li All-Robotics 2010-13
              li Overachiever Forever
          .right-side-honors
            ul
              li Academic Honors 2011-12
              li Scholar Honors 2011-12
              li National Athelete 2010-13
              li Overachiever Forever

app/views/cards/_form.html.slim
= form_for(card) do |f|
  - if card.errors.any?
    #error_explanation
      h2
        = pluralize(card.errors.count, "error")
        | prohibited this card from being saved:
      ul
        - card.errors.full_messages.each do |message|
          li= message
  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :birthday
    = f.date_select :birthday
  .field
    = f.label :location
    = f.text_field :location
  .field
    = f.label :front_image
    = f.text_area :front_image
  .actions
    = f.submit

app/views/cards/edit.html.slim
h1 Editing Card
= render 'form', card: @card
= link_to 'Show', @card
| \
= link_to 'Back', cards_path

app/views/cards/index.html.slim
= render 'homepage/slider'

div.container.homepage-wrapper
  div.row
    div.col-md-12
      h1 Computer Science Trading Cards
      = render @cards

div
  div.col-md-12
    = render 'homepage/homepage_columns'

div
  div.col-md-12
    = render 'homepage/homepage_blocks'

app/views/cards/new.html.slim
h1 New Card
= render 'form', card: @card
= link_to 'Back', cards_path

app/views/cards/show.html.slim
css:
  .player-photo-front { background-image: url("#{@card.front_image}"); }

.container.card-a-tron
  .card
    .face.front
      .team-logo
      .player-photo-front
        .player-number
          | 11
        .player-name-front
          h3 = @card.name
    .face.back
      .player-content-back
        .player-identification-back
          .player-photo-back
          .player-name-back
            = @card.name
        .player-statistics
          .player-position-title
            | Location
            br/
            span.player-position
              = @card.location
          .player-school-title
            | Birthday
            br/
            span.player-school
              = @card.birthday
        .honors-divider
          hr/
          p
            | Achievements
          hr/
        .player-honors
          .left-side-honors
            ul
              li All-District 2011-12
              li All-Conference 2011-12
              li All-Robotics 2010-13
              li Overachiever Forever
          .right-side-honors
            ul
              li Academic Honors 2011-12
              li Scholar Honors 2011-12
              li National Athelete 2010-13
              li Overachiever Forever
        .video-link
          a href="https://www.youtube.com/watch?v=dQw4w9WgXcQ" target="_blank"  Adam Boyet Demo Reel

app/views/homepage/_homepage_blocks.html.slim
      hr.featurette-divider/
      .row.featurette
        .col-md-7
          h2.featurette-heading
            | First featurette heading.
            span.text-muted It'll blow your mind.
          p.lead Donec ullamcorper nulla non metus auctor fringilla. Vestibulum id ligula porta felis euismod semper. Praesent commodo cursus magna, vel scelerisque nisl consectetur. Fusce dapibus, tellus ac cursus commodo.
        .col-md-5
          img.featurette-image.img-fluid.mx-auto alt=("Generic placeholder image") data-src="holder.js/500x500/auto" /
      hr.featurette-divider/
      .row.featurette
        .col-md-7.push-md-5
          h2.featurette-heading
            | Oh yeah, it's that good.
            span.text-muted See for yourself.
          p.lead Donec ullamcorper nulla non metus auctor fringilla. Vestibulum id ligula porta felis euismod semper. Praesent commodo cursus magna, vel scelerisque nisl consectetur. Fusce dapibus, tellus ac cursus commodo.
        .col-md-5.pull-md-7
          img.featurette-image.img-fluid.mx-auto alt=("Generic placeholder image") data-src="holder.js/500x500/auto" /
      hr.featurette-divider/
      .row.featurette
        .col-md-7
          h2.featurette-heading
            | And lastly, this one.
            span.text-muted Checkmate.
          p.lead Donec ullamcorper nulla non metus auctor fringilla. Vestibulum id ligula porta felis euismod semper. Praesent commodo cursus magna, vel scelerisque nisl consectetur. Fusce dapibus, tellus ac cursus commodo.
        .col-md-5
          img.featurette-image.img-fluid.mx-auto alt=("Generic placeholder image") data-src="holder.js/500x500/auto" /
      hr.featurette-divider/

app/views/homepage/_homepage_columns.html.slim
    .container.marketing
      /! Three columns of text below the carousel
      .row
        .col-lg-4
          img.rounded-circle alt=("Generic placeholder image") height="140" src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" width="140" /
          h2 Heading
          p Donec sed odio dui. Etiam porta sem malesuada magna mollis euismod. Nullam id dolor id nibh ultricies vehicula ut id elit. Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Praesent commodo cursus magna.
          p
            a.btn.btn-secondary href="#" role="button"  View details &raquo;
        /! /.col-lg-4
        .col-lg-4
          img.rounded-circle alt=("Generic placeholder image") height="140" src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" width="140" /
          h2 Heading
          p Duis mollis, est non commodo luctus, nisi erat porttitor ligula, eget lacinia odio sem nec elit. Cras mattis consectetur purus sit amet fermentum. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh.
          p
            a.btn.btn-secondary href="#" role="button"  View details &raquo;
        /! /.col-lg-4
        .col-lg-4
          img.rounded-circle alt=("Generic placeholder image") height="140" src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" width="140" /
          h2 Heading
          p Donec sed odio dui. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Vestibulum id ligula porta felis euismod semper. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus.
          p
            a.btn.btn-secondary href="#" role="button"  View details &raquo;

app/views/homepage/_slider.html.slim
    #myCarousel.carousel.slide data-ride="carousel" 
      ol.carousel-indicators
        li.active data-slide-to="0" data-target="#myCarousel" 
        li data-slide-to="1" data-target="#myCarousel" 
        li data-slide-to="2" data-target="#myCarousel" 
      .carousel-inner role="listbox" 
        .carousel-item.active
          = image_tag 'baseball.jpg', width: '100%', class: 'first-slide'
          .container
            .carousel-caption.d-none.d-md-block.text-left
              h1 Example headline.
              p Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.
              p
                a.btn.btn-lg.btn-primary href="#" role="button"  Sign up today
        .carousel-item
          img.second-slide alt=("Second slide") src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" /
          .container
            .carousel-caption.d-none.d-md-block
              h1 Another example headline.
              p Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.
              p
                a.btn.btn-lg.btn-primary href="#" role="button"  Learn more
        .carousel-item
          img.third-slide alt=("Third slide") src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" /
          .container
            .carousel-caption.d-none.d-md-block.text-right
              h1 One more for good measure.
              p Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.
              p
                a.btn.btn-lg.btn-primary href="#" role="button"  Browse gallery
      a.carousel-control-prev data-slide="prev" href="#myCarousel" role="button" 
        span.carousel-control-prev-icon aria-hidden="true" 
        span.sr-only Previous
      a.carousel-control-next data-slide="next" href="#myCarousel" role="button" 
        span.carousel-control-next-icon aria-hidden="true" 
        span.sr-only Next

app/views/layouts/_footer.html.slim
      footer
        p.float-right
          a href="#"  Back to top
        p
          | \&copy; 2017 Company, Inc. &middot;
          a href="#"  Privacy
          | \&middot;
          a href="#"  Terms

app/views/layouts/_nav.html.slim
    nav.navbar.navbar-toggleable-md.navbar-inverse.fixed-top.bg-inverse
      button.navbar-toggler.navbar-toggler-right aria-controls="navbarCollapse" aria-expanded="false" aria-label=("Toggle navigation") data-target="#navbarCollapse" data-toggle="collapse" type="button" 
        span.navbar-toggler-icon
      a.navbar-brand href="#"  Carousel
      #navbarCollapse.collapse.navbar-collapse
        ul.navbar-nav.mr-auto
          li.nav-item.active
            a.nav-link href="#" 
              | Home
              span.sr-only (current)
          li.nav-item
            a.nav-link href="#"  Link
          li.nav-item
            a.nav-link.disabled href="#"  Disabled
        form.form-inline.mt-2.mt-md-0
          input.form-control.mr-sm-2 placeholder="Search" type="text" /
          button.btn.btn-outline-success.my-2.my-sm-0 type="submit"  Search

app/views/layouts/application.html.slim
doctype html
html
  head
    meta content=("text/html; charset=UTF-8") http-equiv="Content-Type" /
    title ComputerScienceCards
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  body

    = render 'layouts/nav'
    = yield
    = render 'layouts/footer'